server:
  port: 8999
# below config for routing url for end points
spring:
  application:
    name: api-gateway
    gateway:
      routes:
        - id: user-serviec
          uri: lb://user-serviec
          predicates:
            - Path=/user/**,/test/**
          filters:
            - name: CircuitBreaker
              args:
               name: user-serviec
               fallbackuri: forward:/userServiceFallback
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
          filters:
             - name: CircuitBreaker
               args:
                name: contact-service
                fallbackuri: forward:/contactServiceFallback


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilleseconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream